name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Change working directory
      run: cd projects  # Change to your project directory

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment
      run: source venv/bin/activate
      
    - name: Set PYTHONPATH
      run: export PYTHONPATH="${PYTHONPATH}:$(pwd)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r algos/requirements.txt
        python -m pip install -r FrontEnd/requirements.txt

    - name: Debug Info
      run: |
        echo "Current working directory: $(pwd)"
        echo "PYTHONPATH: $PYTHONPATH"
        pip list

    - name: Lint with pylint
      run: python -m pylint algos/**/*.py
