name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Activate Python Virtual Environment for Algos
      run: |
        source projects/algos/venv/bin/activate
      shell: bash

    - name: Install Dependencies for Algos
      run: |
        pip install --upgrade pip
        pip install -r projects/algos/requirements.txt
      shell: bash

    - name: Lint Algos with pylint
      run: |
        pylint projects/algos/**/*.py
      shell: bash

    - name: Deactivate Algos Virtual Environment
      run: |
        deactivate
      shell: bash

    - name: Activate Python Virtual Environment for FrontEnd
      run: |
        source projects/FrontEnd/venv/bin/activate
      shell: bash

    - name: Install Dependencies for FrontEnd
      run: |
        pip install --upgrade pip
        pip install -r projects/FrontEnd/requirements.txt
      shell: bash

    - name: Lint FrontEnd with pylint
      run: |
        pylint projects/FrontEnd/**/*.py
      shell: bash

    - name: Deactivate FrontEnd Virtual Environment
      run: |
        deactivate
      shell: bash
