name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r projects/algos/requirements.txt
        python -m pip install -r projects/FrontEnd/requirements.txt

    - name: Lint with pylint
      run: |
        export PYTHONPATH="/Users/Jan/Desktop/Programmering/StocksAlgo/AlgoTrading/projects"
        python -m pylint projects/**/*.py
