name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        python -m pip install -r projects/algos/requirements.txt
        python -m pip install -r projects/algos/utils/requirements.txt

    - name: Lint with pylint
      run: |
        python -m pylint projects utils
