name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python and Create Virtual Environment
      run: |
        python -m venv venv  # Create a virtual environment
      shell: bash

    - name: Activate Virtual Environment
      run: |
        source venv/bin/activate  # Activate the virtual environment on Linux
        # or
        # venv\Scripts\activate  # Activate the virtual environment on Windows
      shell: bash

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r projects/algos/requirements.txt
        pip install -r projects/FrontEnd/requirements.txt
      shell: bash

    - name: Lint with pylint
      run: |
        pylint ${{ github.workspace }}/projects/**/*.py
      shell: bash
